[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/resume"
  to = "/resume/resume.pdf"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
